{% set name = "asana" %}
{% set version = "3.2.0" %}

package:
  name: python-asana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asana-{{ version }}.tar.gz
  sha256: da9275f432ec23c81f7d007493b3f0e03816fd52f4a484f240cce07b439c5d23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - requests >=2.20.0,<3
    - requests-oauthlib >=0.8.0,<2.0

test:
  imports:
    - asana
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/asana/python-asana
  summary: Asana API client
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: http://github.com/asana/python-asana
  doc_url: http://github.com/asana/python-asana

extra:
  recipe-maintainers:
    - xylar
