{% set name = "asana" %}
{% set version = "5.1.0" %}

package:
  name: python-asana
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asana-{{ version }}.tar.gz
  sha256: 9fd565953d771d77be26ee6e0a1c4e117394a1944067b2ee727ff484d004c68e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - certifi >=2017.4.17
    - python-dateutil >=2.1
    - six >=1.10
    - urllib3 >=1.23

test:
  imports:
    - asana
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/asana/python-asana
  summary: Official Python client library for the Asana API v1
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: http://github.com/asana/python-asana
  doc_url: http://github.com/asana/python-asana

extra:
  recipe-maintainers:
    - xylar
