{% set name = "asana" %}
{% set version = "4.0.4" %}

package:
  name: python-asana
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asana-{{ version }}.tar.gz
  sha256: 99b5022fd41a7f4e018bfe82dd24884ba41d540d5014021abb55f56c73f1d37c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - certifi >=2017.4.17
    - python-dateutil >=2.1
    - six >=1.10
    - urllib3 >=1.23

test:
  imports:
    - asana
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/asana/python-asana
  summary: Official Python client library for the Asana API v1
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: http://github.com/asana/python-asana
  doc_url: http://github.com/asana/python-asana

extra:
  recipe-maintainers:
    - xylar
