{% set name = "python-asana" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/asana/asana-{{ version }}.tar.gz
  sha256: 9bfad63deabe0d2855da36a9f98c0f946f759aeaf81642ae9ec1fdc38210b9d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - requests >=2.20.0,<3
    - requests-oauthlib >=0.8.0,<2.0

test:
  imports:
    - asana
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/asana/python-asana
  summary: Asana API client
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: http://github.com/asana/python-asana
  doc_url: http://github.com/asana/python-asana

extra:
  recipe-maintainers:
    - xylar
