{% set name = "python-asana" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Asana/python-asana/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 22a22966b7d01a0a4aad41973333ca3856240f33836ea0c68f0d9448ea045f20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - requests >=2.20.0,<3
    - requests-oauthlib >=0.8.0,<2.0
    - six >=1.10,<2

test:
  imports:
    - asana
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/asana/python-asana
  summary: Asana API client
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: http://github.com/asana/python-asana
  doc_url: http://github.com/asana/python-asana

extra:
  recipe-maintainers:
    - xylar
