schema_version: 1

context:
  name: asana
  version: "5.3.0"

package:
  name: python-asana
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/asana-${{ version }}.tar.gz
  sha256: c267ce27de2fd2283111463ca44b2f2ac862c81f7f09918db6721727d7bbb0ee

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - certifi >=2017.4.17
    - python-dateutil >=2.1
    - six >=1.10
    - urllib3 >=1.23

tests:
  - python:
      imports:
        - asana
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  summary: Official Python client library for the Asana API v1
  license: MIT
  license_file: LICENSE
  homepage: http://github.com/asana/python-asana
  repository: http://github.com/asana/python-asana
  documentation: http://github.com/asana/python-asana

extra:
  recipe-maintainers:
    - xylar
